In [1]:
from numpy import asarray
from keras.models import Sequential
from keras.layers import UpSampling2D

### define input data
X = asarray([[1, 2],
            [3, 4]])
print(X)
### reshape input data 
X = X.reshape((1, 2, 2, 1))
# print(X)
model = Sequential()
model.add(UpSampling2D(input_shape=(2, 2, 1)))
model.summary()
# make a prediction with the model
yhat = model.predict(X)
# reshape output to remove channel to make printing easier
yhat = yhat.reshape((4, 4))
# summarize output
print(yhat)

Using TensorFlow backend.
[[1 2]
 [3 4]]



_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________



[[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]


## Upsampling


In [5]:
import tensorflow as tf
import numpy as np

input_shape = (1, 2, 2, 1) # batch, height, width, channels
x = np.arange(1, 5, 1).reshape(input_shape)
print('x \n', x)
upLayer = tf.keras.layers.UpSampling2D(size=(2, 2))
y = upLayer(x)
print('y: \n', y)

x 
 [[[[1]
   [2]]

  [[3]
   [4]]]]
&lt;class &#39;tensorflow.python.framework.ops.Tensor&#39;&gt;
y: 
 Tensor(&quot;up_sampling2d_2/ResizeNearestNeighbor:0&quot;, shape=(1, 4, 4, 1), dtype=int64)


## Bilinear

In [3]:
import tensorflow as tf
import numpy as np

input_shape = (1, 2, 2, 1) # batch, height, width, channels
x = np.arange(1, 5, 1).reshape(input_shape)
print('x \n', x)
upLayer = tf.keras.layers.UpSampling2D(size=(2, 2), interpolation='bilinear')
y = upLayer(x)
print('y: \n', y)

x 
 [[[[1]
   [2]]

  [[3]
   [4]]]]
y: 
 Tensor(&quot;up_sampling2d_1_1/ResizeBilinear:0&quot;, shape=(1, 4, 4, 1), dtype=float32)
